### ISSUE TITLE
sublime text 2 + phpcs : I-invalid file syntax, file ignored

### ISSUE THREAD

**Issue by Ditwo** [benmatselby/sublime-phpcs#159] opened 2016-08-24 14:52 UTC
Hello,

Despite a lot of time spent on forums I am not able to find out a solution. I hope somebody could help me !

Here is the console of sublime text : 
> [Phpcs] Fixer
> [Phpcs] C:\wamp\bin\php\php5.5.12\php.exe C:\wamp\tools\php-cs-fixer.phar fix E:\test.php --verbose
> [Phpcs] You are running php-cs-fixer with xdebug enabled. This has a major impact on runtime performance.
> > I
> > Legend: ?-unknown, I-invalid file syntax, file ignored, .-no changes, F-fixed, E-error
> > Fixed all files in 0.217 seconds, 5.250 MB memory used

Even this short code could not be fixed : 
```
<?php
echo 'hello';
```
My config : 
PHP version 5.5.12, Apache 2.4.9
PHPCS v2016.06.04.20.4.4.08
Sublime Text 2
Windows 10 + Wampserver

Any help would be appreciated.
Regards
Denis

**Comment by benmatselby** [comment] 2016-08-30 15:26
Hi @Ditwo. This is a duplicate of https://github.com/benmatselby/sublime-phpcs/issues/140 which currently has no further update.

**Closed by benmatselby** 2016-08-30 15:26 UTC
